zuul:
  sslHostnameValidationEnabled: false
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 20000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 10000
ribbon:
  ConnectTimeout: 20000
  ReadTimeout: 20000