security:
  oauth2:
    resource:
      jwt:
        key-value: mysecret
spring:
  datasource:
    url: jdbc:mysql://r-gun-nas:3307/cloud?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: common
    password: common1122334455
    hikari:
      maxLifetime: 1800000
      idleTimeout: 60000
      connectionTimeout: 30000
      maximumPoolSize: 20
      minimum-idle: 10
